config/routes.rb
Rails.application.routes.draw do
  root  "articles#index"
  get "/articles/:id/edit", to: "articles#edit"
  post "/articles", to: "articles#create"
  get "/articles/new", to: "articles#new"
  get "/articles", to: "articles#index"
  get "/articles/:id", to: "articles#show", as: :article
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @articles = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    if @article.save
    redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])

  end

  private

  def articles_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>
<%= form.label :content %>
<%= form.text_area :content %>
<%= form.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>This is our index page</h1>
<% @articles.each do |article| %>
<strong> <%= article.title %> </strong>
<p> <%= article.content %> </p>
<%= link_to "Show", article_path(article.id)%>
<% end %>
<%= link_to "New", articles_new_path %>

app/views/articles/new.html.erb
<h1> New Article </h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<strong> <%= @articles.title %> </strong>
<p> <%= @articles.content %> </p>
<%= link_to "HomePage", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>